version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    build: ./web
    env_file: ./.env.dev
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./web/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
