# Generated by Django 3.1.7 on 2021-03-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0002_auto_20210310_1635"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="type",
            field=models.IntegerField(choices=[(0, "Todo"), (1, "Done")], default=0),
        ),
    ]
