# Generated by Django 3.1.7 on 2021-03-10 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0004_auto_20210310_1809"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todo",
            name="due",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
