# Generated by Django 3.1.7 on 2021-03-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0005_auto_20210310_1845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="due",
            field=models.DateTimeField(),
        ),
    ]
