# Generated by Django 3.1.7 on 2021-03-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0003_todo_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["type", "title"]},
        ),
    ]
